[workspace]
members = [
    "crates/wanix-agent",
    "crates/wanix-appfs",
    "crates/wanix-cas",
    "crates/wanix-cli",
    "crates/wanix-cpu",
    "crates/wanix-9p",
    "crates/wanix-9p-client",
    "crates/wanix-fs",
    "crates/wanix-id",
    "crates/wanix-job",
    "crates/wanix-kv",
    "crates/wanix-mesh",
    "crates/wanix-mesh-wire",
    "crates/wanix-module-cache",
    "crates/wanix-pipe",
    "crates/wanix-plumb",
    "crates/wanix-protocol",
    "crates/wanix-qjs",
    "crates/wanix-qjs-engine",
    "crates/wanix-sh",
    "crates/wanix-site-cas",
    "crates/wanix-site-fs",
    "crates/wanix-site-gen",
    "crates/wanix-sites",
    "crates/wanix-task",
    "crates/wanix-term",
    "crates/wanix-tool",
    "crates/wanix-vfs",
    "crates/wanix-wasi",
    "crates/wanix-wasi-host",
    "crates/wanix-wasm",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/tractordev/wanix"
rust-version = "1.93"
version = "0.1.0"

[workspace.lints.rust]
missing_docs = "warn"
