use super::CliOutput;

pub(super) const USAGE: &str = concat!(
    "usage: wanix-rust qjs [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--stdin TEXT | --stdin-file PATH|-] [--event-loop-ms N] [--ready-io-turns N] ",
    "[--interrupt-after N] [--memory-limit-bytes N] ",
    "[--mount HOST=GUEST ...] <script.js> [-- arg ...]\n",
    "       wanix-rust qjs-term [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--stdin TEXT | --stdin-file PATH|-] [--event-loop-ms N] [--ready-io-turns N] ",
    "[--feed-after-eval TEXT ...] [--feed-after-eval-file PATH|- ...] ",
    "[--feed-after-eval-lines PATH|- ...] ",
    "[--resize-after-eval COLSxROWS ...] ",
    "[--interrupt-after N] [--memory-limit-bytes N] ",
    "[--mount HOST=GUEST ...] <script.js> [-- arg ...]\n",
    "       wanix-rust qjs-shell [--raw] [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--event-loop-ms N] [--ready-io-turns N] ",
    "[--interrupt-after N] [--memory-limit-bytes N] ",
    "[--mount HOST=GUEST ...] [--mount-mesh IROH_URL=GUEST ...]\n",
    "       wanix-rust qjs-snapshot [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--stdin TEXT | --stdin-file PATH|-] [--interrupt-after N] ",
    "[--memory-limit-bytes N] [--event-loop-ms N] [--ready-io-turns N] ",
    "[--mount HOST=GUEST ...] ",
    "--snapshot FILE <script.js> [-- arg ...]\n",
    "       wanix-rust qjs-resume [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--stdin TEXT | --stdin-file PATH|-] [--interrupt-after N] ",
    "[--memory-limit-bytes N] [--event-loop-ms N] [--ready-io-turns N] ",
    "[--mount HOST=GUEST ...] ",
    "--snapshot FILE <script.js> [-- arg ...]\n",
    "       wanix-rust qjs-restore [--cwd DIR] [--before-env KEY=VALUE ...] ",
    "[--after-env KEY=VALUE ...] [--before-arg VALUE ...] [--after-arg VALUE ...] ",
    "[--mount HOST=GUEST ...] <before.js> <after.js>\n",
    "       wanix-rust wasm [--env KEY=VALUE ...] [--cwd DIR] ",
    "[--stdin TEXT | --stdin-file PATH|-] FILE.wasm [args...] ",
    "(command-style WASI subset, no poll readiness; .wasm is also a first-class Wanix task driver)\n",
    "       wanix-rust p9-stdio --root DIR\n",
    "       wanix-rust mesh-serve (--root DIR | --volume NAME) [--key FILE] [--addr IP:PORT] ",
    "[--peer HEX --grant ANAME:PREFIX:RIGHTS ...] [--wanix-services] [--insecure-open]\n",
    "         (--wanix-services binds the #task/#agent exec devices = remote code execution; ",
    "local-trust only, so it requires --addr IP:PORT and is refused on the public endpoint. ",
    "--insecure-open exports the host directory read-write, NOT the exec devices, to anyone with the ticket)\n",
    "       wanix-rust cpu --node iroh://PEER[?addr=IP:PORT] [--cwd DIR] [--write] ",
    "[--env KEY=VALUE ...] -- KIND PROGRAM [ARG ...]\n",
    "         (Plan 9 cpu over the mesh: reverse-exports DIR read-only by default and runs ",
    "KIND PROGRAM on the data node against it; --write opts the export into read-write)\n",
    "       wanix-rust mount-ls (tcp://HOST:PORT | iroh://PEER[?addr=IP:PORT]) [PATH]\n",
    "       wanix-rust mount-cat (tcp://HOST:PORT | iroh://PEER) PATH\n",
    "       wanix-rust mount-write (tcp://HOST:PORT | iroh://PEER) PATH TEXT\n",
    "       wanix-rust rootfs --archive FILE.tgz --out DIR [--json]\n",
    "       wanix-rust new (--js NAME | --rust NAME) [--dir DIR]\n",
    "       wanix-rust volume (create NAME | ls)   (persistent volumes under ~/.wanix/volumes)\n",
    "       wanix-rust volume serve (--volume NAME ... | --all) [--addr IP:PORT] [--insecure-open]",
    "   (one mesh endpoint + ticket per volume; use --addr port 0 for multiple)\n",
    "       wanix-rust agent [--fake] [--cwd DIR] [--world DIR] <prompt>\n",
    "       wanix-rust capsule (save DIR | load CAPSULE_ID DIR) [--store DIR]\n",
    "       wanix-rust qemu --root DIR [--kernel PATH] [--initrd PATH] [--cmdline TEXT] [--append TEXT ...] ",
    "[--qemu-bin PATH] [--memory-mb N] ",
    "[--mount-tag TAG] [--security-model MODEL] [--p9-msize N] ",
    "[--json] [--no-kvm] [--exec]\n",
    "       wanix-rust serve [--root DIR | DIR] [--listen HOST:PORT] ",
    "[--p9 HOST:PORT [--peer HEX --grant ANAME:PREFIX:RIGHTS ...]] ",
    "[--bundle NAME] [--wanix-services] [--once]\n",
    "       wanix-rust --help",
);

pub(super) fn help_output() -> CliOutput {
    CliOutput::new(
        format!("wanix-rust: {}\n{USAGE}\n", wanix_qjs::FIRST_DEMO_TARGET).into_bytes(),
        Vec::new(),
        0,
    )
}
