[package]
name = "wanix-kv"
description = "Key/value service filesystem for the Rust-native Wanix port."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
wanix-fs = { path = "../wanix-fs" }

[lib]
name = "wanix_kv"
path = "src/lib.rs"

[lints]
workspace = true
