[package]
name = "wanix-qjs"
description = "QuickJS/WASI task driver for Rust-native Wanix."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = "1"
rust_wasi_quickjs = { package = "wanix-qjs-engine", path = "../wanix-qjs-engine" }
serde_json = "1"
wanix-fs = { path = "../wanix-fs" }
wanix-task = { path = "../wanix-task" }
wanix-wasi = { path = "../wanix-wasi" }
wasmtime = { version = "45.0.0", default-features = false, features = [
    "anyhow",
    "cranelift",
    "runtime",
    "std",
    "wat",
] }

[dev-dependencies]
wanix-vfs = { path = "../wanix-vfs" }

[lib]
name = "wanix_qjs"
path = "src/lib.rs"

[lints]
workspace = true
