;; Synthetic minimal QuickJS ABI fixture; keep exports in sync with
;; src/module/abi/spec.rs.
(module
  (memory (export "memory") 1)
  (global $__stack_pointer (export "__stack_pointer") (mut i32) (i32.const 65536))

  (func (export "_initialize"))
  (func (export "qjs_init") (result i32)
    i32.const 0)
  (func (export "qjs_destroy"))
  (func (export "qjs_eval")
    (param $code i32)
    (param $code_len i32)
    (param $filename i32)
    (param $flags i32)
    (result i32)
    i32.const 4)
  (func (export "qjs_new_string") (param $ptr i32) (param $len i32) (result i32)
    i32.const 40)
  (func (export "qjs_get_undefined") (result i32)
    i32.const 30)
  (func (export "qjs_get_global") (result i32)
    i32.const 10)
  (func (export "qjs_get_prop_string") (param $global i32) (param $name i32) (result i32)
    i32.const 20)
  (func (export "qjs_call")
    (param $function i32)
    (param $this_value i32)
    (param $argc i32)
    (param $argv i32)
    (result i32)
    i32.const 50)
  (func (export "qjs_is_exception") (param $value i32) (result i32)
    i32.const 0)
  (func (export "qjs_is_number") (param $value i32) (result i32)
    i32.const 0)
  (func (export "qjs_is_string") (param $value i32) (result i32)
    i32.const 1)
  (func (export "qjs_get_exception") (result i32)
    i32.const 60)
  (func (export "qjs_get_float64") (param $value i32) (result f64)
    f64.const 0)
  (func (export "qjs_get_string") (param $value i32) (result i32)
    i32.const 1200)
  (func (export "qjs_free_cstring") (param $ptr i32))
  (func (export "qjs_free_value") (param $value i32))
  (func (export "qjs_is_job_pending") (result i32)
    i32.const 0)
  (func (export "qjs_execute_pending_job") (result i32)
    i32.const 0)
  (func (export "qjs_get_runtime_ptr") (result i32)
    i32.const 256)
  (func (export "qjs_get_context_ptr") (result i32)
    i32.const 512)
  (func (export "qjs_set_runtime_and_context") (param $runtime i32) (param $context i32))
  (func (export "wasm_malloc") (param $size i32) (result i32)
    i32.const 4096)
  (func (export "wasm_free") (param $ptr i32))
)
